### ISSUE TITLE
feat: Update AHS examples that utilize ahs_utils methods

### ISSUE THREAD

**Issue by ykharkov** [amazon-braket/amazon-braket-examples#270]
In PR [#508](https://github.com/aws/amazon-braket-sdk-python/pull/508) we moved functionality realized in ahs_utils.py to BDK.

The next step is to update all AHS examples, that utilze result.get_counts(), result.get_avg_density(), TimeSeries.from_lists() etc.
This will make the Jupyter notebooks more concise and more readable.

**Comment by kshitijc** [comment]
Closing since #315  has been merged.
