### ISSUE TITLE
The request to AWS Cost Explorer client asking for the cost of a job given by ARN returns 0$

### ISSUE THREAD

**Issue by balewski** [amazon-braket/amazon-braket-examples#296]
The request to AWS Cost Explorer client  asking for the cost of a job given by ARN returns 0$

**To Reproduce**
execute the script:
https://bitbucket.org/balewski/quantummind/src/master/QuEra/python/issues/issue2_cost_by_ARN.py

**Expected behavior**
for  the day June 15 there should be a charge of about $1.5
I can see the job completed here:
https://us-east-1.console.aws.amazon.com/braket/home?region=us-east-1#/tasks/arn%3Aaws%3Abraket%3Aus-east-1%3A765483381942%3Aquantum-task%2F484a891b-828d-4127-9853-a447c09880ab 

**System information (please complete the following information as applicable):**
$ pip3 list |grep braket
amazon-braket-default-simulator 1.15.0
amazon-braket-schemas           1.17.0
amazon-braket-sdk               1.42.1

 **Known workaround (if applicable)**
 read number of shots on the AWS web page and use calculator to compute the cost

**Comment by guomanmin** [comment]
Looking into reproing this issue

**Comment by guomanmin** [comment]
Hi @balewski  - according to AWS Cost Explorer documentation https://aws.amazon.com/aws-cost-management/aws-cost-explorer/features/, the the cost reporting is at daily or monthly granularity. Could you confirm is this issue repros even 24 hours later?

**Comment by balewski** [comment]
At the time of submitting this ticket it was already several day past the date of execution of the AHS program. But to double check I run it today and still I see there is no charge for June 15. Since it is not clear which time zones are used for charging purposes I printed also 1 day before and after - all 3 days report $0 charges. It is 25 days past the usage.
I see:
 ```
{'Estimated': False,
                    'Groups': [],
                    'TimePeriod': {'End': '2023-06-15', 'Start': '2023-06-14'},
                    'Total': {'AmortizedCost': {'Amount': '0', 'Unit': 'USD'}}},
                   {'Estimated': False,
                    'Groups': [],
                    'TimePeriod': {'End': '2023-06-16', 'Start': '2023-06-15'},
                    'Total': {'AmortizedCost': {'Amount': '0', 'Unit': 'USD'}}},
                   {'Estimated': False,
                    'Groups': [],
                    'TimePeriod': {'End': '2023-06-17', 'Start': '2023-06-16'},
                    'Total': {'AmortizedCost': {'Amount': '0',
                                                'Unit': 'USD'}}}]}
$ date
Tue Jul 11 06:24:28 PDT 2023
```

**Comment by speller26** [comment]
Hello, I'm carrying on Angela's investigation. If you go to the AWS Cost Explorer in the AWS Console and go to Cost Explorer, does any cost information appear in the graph when you filter "Service" to only include Braket? And if so, does "USE1-Job-QPU-Task-Shot-QuEra-Aquila (Quantum-Shot)" under the "Usage type" filter?

**Comment by balewski** [comment]
Answer for question 1: when I enter page: AWS Cost Management I see message 'You are not authorized to perform this operation.'  

Answering Q2:
Running the code you provided gives me some non-zero values for the 3 days QuEra is running the service - this is good progress.  And the amounts of ~$10 make sense. I see:
```
{'DimensionValueAttributes': [],
 'ResponseMetadata': {'HTTPHeaders': {'cache-control': 'no-cache',
                                      'connection': 'keep-alive',
                                      'content-length': '761',
                                      'content-type': 'application/x-amz-json-1.1',
                                      'date': 'Fri, 14 Jul 2023 04:35:07 GMT',
                                      'x-amzn-requestid': '6c9b81c9-6c03-4803-ade9-a3fad2f5f575'},
                      'HTTPStatusCode': 200,
                      'RequestId': '6c9b81c9-6c03-4803-ade9-a3fad2f5f575',
                      'RetryAttempts': 0},
 'ResultsByTime': [{'Estimated': False,
                    'Groups': [],
                    'TimePeriod': {'End': '2023-06-13', 'Start': '2023-06-12'},
                    'Total': {'AmortizedCost': {'Amount': '0', 'Unit': 'USD'}}},
                   {'Estimated': False,
                    'Groups': [],
                    'TimePeriod': {'End': '2023-06-14', 'Start': '2023-06-13'},
                    'Total': {'AmortizedCost': {'Amount': '21.1',
                                                'Unit': 'USD'}}},
                   {'Estimated': False,
                    'Groups': [],
                    'TimePeriod': {'End': '2023-06-15', 'Start': '2023-06-14'},
                    'Total': {'AmortizedCost': {'Amount': '7.9',
                                                'Unit': 'USD'}}},
                   {'Estimated': False,
                    'Groups': [],
                    'TimePeriod': {'End': '2023-06-16', 'Start': '2023-06-15'},
                    'Total': {'AmortizedCost': {'Amount': '1.3',
                                                'Unit': 'USD'}}},
                   {'Estimated': False,
                    'Groups': [],
                    'TimePeriod': {'End': '2023-06-17', 'Start': '2023-06-16'},
                    'Total': {'AmortizedCost': {'Amount': '0',
                                                'Unit': 'USD'}}}]}
```
So it looks this code lists  aggregated daily charge. We are 3/4 of the way to the goal. Would you know how to add filtering by job ARN? Or simply print all job ARNs and individual costs? I can do the filtering.

**Comment by laurencap** [comment]
Closing as resolved. If the suggested fix didn't resolve your issue, please reopen with additional information. Thank you!
