### ISSUE TITLE
 AwsQuantumJob  for QuEra has incomplete software stack

### ISSUE THREAD

**Issue by balewski** [amazon-braket/amazon-braket-examples#299]
**Describe the bug**
Attached example should submit, execute, and measure the cost of a hybrid job running on AWS and the QuEra QPU.
It encountered 3 problems:

1. quera_ahs_utils module does not exist in the image started on AWS by  AwsQuantumJob.create(..)
(after I hacked it)
2. AttributeError: 'AnalogHamiltonianSimulationQuantumTaskResult' object has no attribute 'get_counts',
meaning the version of amazon-braket-sdk on the image is far behind https://amazon-braket-sdk-python.readthedocs.io/en/latest/index.html
(after I hacked that)
3. The cost tracking is not working, because for a successfully executed task on Aquila (which is not free) this code 
```
 with Tracker() as tracker:
                full_task(device,ahs_prog,shots)
                print('cost tracker, charge/$:',tracker.simulator_tasks_cost())
```
run against : 
deviceArn='arn:aws:braket:us-east-1::device/qpu/quera/Aquila'
results with the output:
cost tracker, charge/$: 0

**To Reproduce**
1. pull this 2 files:
https://bitbucket.org/balewski/quantummind/src/master/QuEra/python/issues/hybrid_task.py
https://bitbucket.org/balewski/quantummind/src/master/QuEra/python/issues/hybrid_submit.py
2. execute the script 
```python hybrid_submit.py```

**Expected behavior**
there is no crash and the printed cost is 0.60 $

 **Known workaround (if applicable)**
 I can cut out get_drive(.) and get_counts(.) functions from the Amazon Braket Python SDK 'stable' version and place them in my code.

**Comment by guomanmin** [comment]
Looking into reproing this issue

**Comment by guomanmin** [comment]
Just running the hybrid_submit.py has been stucked at "Initializing Braket Job" for me so far. Still Investigating.

**Comment by balewski** [comment]
indeed, now it never passe the . . . ., this is what I see.
But at the time of filing this ticket  the image would start after ~15 dots, then I'd get the crash.

```
Initializing Braket Job: arn:aws:braket:us-east-1:765483381942:job/braket-job-default-1689116339095
..........................................................................................................................................................................................................................................................................
```

**Comment by balewski** [comment]
Hi Cody,
I think there is an order of issues.

1) I can't start the hybrid task any more . I see infinite number of '.....'
$ ./hybrid_submit.py
Initializing Braket Job: arn:aws:braket:us-east-1:765483381942:job/braket-job-default-1689619362712
.........................

Until this is resolved the rest does not matter.
I'm using the same script as before:
https://bitbucket.org/balewski/quantummind/src/master/QuEra/python/issues/hybrid_submit.py
Were you able to submit a hybrid task against: 
deviceArn='arn:aws:braket:us-east-1::device/qpu/quera/Aquila'
?

2) Here is my local software stack shown as you requested:
$ pip show amazon-braket-sdk
Name: amazon-braket-sdk
Version: 1.49.0
Summary: An open source library for interacting with quantum computing devices on Amazon Braket
Home-page: https://github.com/aws/amazon-braket-sdk-python
Author: Amazon Web Services
Author-email: 
License: Apache License 2.0
Location: /usr/local/lib/python3.10/dist-packages
Requires: amazon-braket-default-simulator, amazon-braket-schemas, backoff, boltons, boto3, nest-asyncio, networkx, numpy, openpulse, openqasm3, oqpy, setuptools, sympy
Required-by: quera-ahs-utils

2.1) here are more details about it
$ pip3 list|grep amazon
amazon-braket-default-simulator 1.18.2
amazon-braket-schemas           1.18.0
amazon-braket-sdk               1.49.0
$pip3 list|grep ahs   
quera-ahs-utils                 0.4.3

3) yes, I can start & run this task locally. I have modified the main() in it, 
 https://bitbucket.org/balewski/quantummind/src/master/QuEra/python/issues/hybrid_task.py
and local execution works:
$ ./hybrid_task.py 
...
COMPLETED, rawBitstr:
{'grgrgrggrgr': 3,
 'rggrggrgrgr': 2,
 'rggrgrggrgr': 9,
 'rggrgrgrggr': 5,
 'rgrgggrgrgr': 1,
 'rgrggrggrgr': 26,
 'rgrggrgrggr': 7,
 'rgrggrgrgrg': 4,
 'rgrgrggrgrg': 4,
 'rgrgrgrgggr': 1,
 'rgrgrgrgrgr': 38}

Thanks
Jan

**Comment by speller26** [comment]
> 2.1) here are more details about it
$ pip3 list|grep amazon
amazon-braket-default-simulator 1.18.2
amazon-braket-schemas           1.18.0
amazon-braket-sdk               1.49.0
$pip3 list|grep ahs
quera-ahs-utils                 0.4.3

I think this is your environment rather than the job environment; the library versions may be different between the two. As for the jobs themselves, the long initialization may be due to the job being stuck in a job queue; can you verify whether your job has completed?

**Comment by balewski** [comment]
yes, this is my local environment. This is all what I can do now.

As I mentioned ,I can't start a hybrid  job for 5-10 minutes any more. I do not have patience to wait longer.
This 1 time when the hybrid job started  for me I could observe the stages:
The initial .... stopped  and then some image on AWS started, there was a message about it. Next the image accepted my QuEra python code and then I could see it submitted the Aquila job to QuEra, which I could observe via AWS web service as   QUEUED. I could also kill this job via AWS web and then on my terminal I'd see the results form killed job returned by the image running on AWS.

But I can't do it any more. The AWS image never reports as working.
It is all in your court now. I can do nothing until you manage to start the  AWS image.
Can you start it?
Do you see 
￼

as described
https://docs.aws.amazon.com/braket/latest/developerguide/braket-jobs-first.html￼

This message should show up even if my QuEra task is wrong - it reports the image has started 
Jan

**Comment by speller26** [comment]
> yes, this is my local environment. This is all what I can do now. As I mentioned ,I can't start a hybrid job for 5-10 minutes any more. I do not have patience to wait longer. This 1 time when the hybrid job started for me I could observe the stages: The initial .... stopped and then some image on AWS started, there was a message about it. Next the image accepted my QuEra python code and then I could see it submitted the Aquila job to QuEra, which I could observe via AWS web service as QUEUED. I could also kill this job via AWS web and then on my terminal I'd see the results form killed job returned by the image running on AWS. But I can't do it any more. The AWS image never reports as working. It is all in your court now. I can do nothing until you manage to start the AWS image. Can you start it?

In your [code snippet](https://bitbucket.org/balewski/quantummind/src/c2857a112a15f2cc823ab24065d151afd3734020/QuEra/python/issues/hybrid_submit.py#lines-21), you have the line
```python
wait_until_complete=True
```
which causes the `.........` to appear and block your Python process. If you run
```python
job = AwsQuantumJob.create(
    deviceArn,
    source_module="hybrid_task.py",
    entry_point="hybrid_task:start_here",
)
``` 
the job will still be created, and you can access its status with
```python
job.state()
```
The wait is unfortunately out of our control; it depends on the number of customers who also have jobs queued up.

>Do you see ￼ as described [https://docs.aws.amazon.com/braket/latest/developerguide/braket-jobs-first.html￼](https://docs.aws.amazon.com/braket/latest/developerguide/braket-jobs-first.html) This message should show up even if my QuEra task is wrong - it reports the image has started Jan

I don't see the image you posted, but if it's a message output (like the `Test job started!!!!!` in your script) will not appear past the `......` while the job is in the QUEUED state.

<img width="1369" alt="image" src="https://github.com/aws/amazon-braket-examples/assets/15883075/417aa655-d56c-49f8-af57-50c0ca87841a">

**Comment by speller26** [comment]
To diagnose versioning issues, would you be able to run this script
```python
import os
import numpy as np
from pprint import pprint
from decimal import Decimal

from braket import _schemas, _sdk, default_simulator
from braket.ahs import AtomArrangement, DrivingField, Hamiltonian, AnalogHamiltonianSimulation
from braket.devices import LocalSimulator
from braket.aws import AwsDevice
from braket.tracking import Tracker

#...!...!....................
def ahs_problem():
    a = 6.1e-6  # meters
    N_atoms = 11

    register = AtomArrangement()
    for i in range(N_atoms):   register.add([0.0, i*a])

    print('\nM:dump atom coordinates')
    
    xL=register.coordinate_list(0)
    yL=register.coordinate_list(1)
    
    for x,y in zip(xL,yL):  print(x,y)

    H = Hamiltonian()
    
    omega_max = 2e6 * 2 * np.pi
    detuning_min = -9e6 * 2 * np.pi
    detuning_max = 7e6 * 2 * np.pi
    
    time_max = Decimal('4')/1000000 # 4 us
    time_ramp =time_max/4

    # rounding is required for Aquila
    omega_max=int(omega_max/400)*400
    detuning_min=int(detuning_min*5)/5
    detuning_max=int(detuning_max*5)/5
    
    time_points = [0, time_ramp, time_max - time_ramp, time_max]
    omega_values = [0, omega_max, omega_max, 0]
    detuning_values = [detuning_min, detuning_min, detuning_max, detuning_max]
    phase_values = [0, 0, 0, 0]

    drive = DrivingField.from_lists(time_points, omega_values, detuning_values, phase_values)
    H += drive

    print('\nM:dump drive Amplitude :\n',drive.amplitude.time_series.times(), drive.amplitude.time_series.values())

    program = AnalogHamiltonianSimulation(  register=register, hamiltonian=H)

    return program

#...!...!....................
def full_task(device,ahs_prog,shots):
    task = device.run(ahs_prog, shots=shots)
    results=task.result()  # this forces wait for task completion/terminationcost tracking
    print('status=%s:'%task.state())
    
    if task.state()=='COMPLETED': 
        rawBitstr=results.get_counts()
        print('COMPLETED, rawBitstr:');  pprint(rawBitstr)
       
#...!...!....................
def start_here():    
    print("Test job started!!!!!")
    print("Versions:")  # See the versions of the Braket libraries in your image
    print(f"schemas: {_schemas.__version__}")
    print(f"SDK: {_sdk.__version__}")
    print(f"default simulator: {default_simulator.__version__}")
    # Use the device declared in the job script
    device = LocalSimulator("braket_ahs")
    print('M:device is braket_ahs')
    ahs_prog=ahs_problem()
    shots=100

    print("M:Test job completed!!!!!")

if __name__ == "__main__":
    start_here()
```
and run said script locally (assuming the same filename as your script):
```python
from braket.jobs.local import LocalQuantumJob

job = LocalQuantumJob.create(
    device="local:amazon/braket_ahs,
    source_module="hybrid_task.py",
    entry_point="hybrid_task:start_here",
)
```
This will try to run your script on the local simulator, as well as print out the versions of the libraries in the container image.

**Comment by balewski** [comment]
Hi Cody,
the local execution fails. I'm guessing local_job_container.py assumes access to Docker. I do not use Docker but Podman.
And the command "podman images -q" works only form outside of the image.
 I'm not sure how how to proceed with this test. Also, you have not answered if you were able to run this test yourself successfully.

Anyhow,  for clarity, this is the setup on my MAC-OS.
1) I start podman deamon:
$  podman machine start 
2) I start podman image:
IMG=balewski/ubu22-braket-quera:v2
$ podman run -it $IMG /bin/bash

3) inside running container I have this software stack:
***@***.***:~/issues/test1$ pip3 list|grep amazon
amazon-braket-default-simulator 1.18.2
amazon-braket-schemas           1.18.0
amazon-braket-sdk               1.49.0

4) in the same instance I run your version of QuEra code (from the previous e-mail)

4.1) tesitng of the 'payload' task works
***@***.***:~/issues/test1$ python3 hybrid_task2.py
....
M:dump drive Amplitude :
 [0, Decimal('0.000001'), Decimal('0.000003'), Decimal('0.000004')] [0, 12566000, 12566000, 0]
M:Test job completed!!!!!

4.2) local run of the hybrid job fails:

***@***.***:~/issues/test1$ python3 hybrid_submit2.py
Traceback (most recent call last):
  File "/quera/issues/test1/hybrid_submit2.py", line 5, in <module>
    job = LocalQuantumJob.create(
  File "/usr/local/lib/python3.10/dist-packages/braket/jobs/local/local_job.py", line 148, in create
    with _LocalJobContainer(
  File "/usr/local/lib/python3.10/dist-packages/braket/jobs/local/local_job_container.py", line 57, in __enter__
    self._container_name = self._start_container(self.image_uri, self._force_update)
  File "/usr/local/lib/python3.10/dist-packages/braket/jobs/local/local_job_container.py", line 148, in _start_container
    image_name = self._check_output_formatted(["docker", "images", "-q", image_uri])
  File "/usr/local/lib/python3.10/dist-packages/braket/jobs/local/local_job_container.py", line 94, in _check_output_formatted
    output = subprocess.check_output(command)
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'docker'
***@***.***:~/issues/test1$ 
Back to you
Jan

**Comment by balewski** [comment]
Follow up,
I run another test. I have asked running image for its name:
***@***.***:~/issues/test1$ hostname
da6346042b58

Next, I modified the hybrid job script to be

$ cat hybrid_submit2.py
from braket.jobs.local import LocalQuantumJob

job = LocalQuantumJob.create(
    device="da6346042b58:amazon/braket_ahs",
    source_module="hybrid_task2.py",
    entry_point="hybrid_task2:start_here",
)

And got the same crash:
....
 File "/usr/local/lib/python3.10/dist-packages/braket/jobs/local/local_job_container.py", line 148, in _start_container
    image_name = self._check_output_formatted(["docker", "images", "-q", image_uri])
...

**Comment by balewski** [comment]
Hi,
is there any resolution for this problem?
Thanks
Jan

**Comment by speller26** [comment]
Hi Jan,

We're very sorry for the delay in getting back to you. You should be able to run your script now, _with modifications_. First, there is no need to use `quera_ahs_utils.drive.get_drive` anymore; in fact, you can replace the import block
```python
from braket.ahs.atom_arrangement import AtomArrangement
from braket.ahs.hamiltonian import Hamiltonian
from braket.ahs.analog_hamiltonian_simulation import AnalogHamiltonianSimulation
from quera_ahs_utils.drive import get_drive
```
with just
```python
from braket.ahs import AnalogHamiltonianSimulation, AtomArrangement, DrivingField, Hamiltonian
```
and then replace
```python
drive = get_drive(time_points, omega_values, detuning_values, phase_values)
```
with
```python
drive = DrivingField.from_lists(time_points, omega_values, detuning_values, phase_values)
```
With these modifications, I can now run the job, and it gets to the
```
M:executing
```
print statement, which means that the `DrivingField.from_lists` is successful. Since `from lists` was introduced in the same change that added `get_counts` to `AnalogHamiltonianSimulationQuantumTaskResult`, this gives me some confidence that the rest of the job should run too.

I believe the issue was fixed with https://github.com/amazon-braket/amazon-braket-sdk-python/pull/643, so pulling in the latest Amazon Braket SDK should do the trick.

As for the example I gave you, Docker is a requirement for running local jobs, so that might be the reason it didn't work.

**Comment by balewski** [comment]
Hi Cody,
No worries, I know we are all oversubscribed. To shorten the path to success could you point me to the full instruction on Amazon web site describing how to run a hybrid job on QuEra  Aquila HW?
The devil is in the details. You could pick some simple problem, say 5 atoms on a line, a common drive Hamiltonian. Run this circuit 3 times in a loop sitting on a CPU, each time exciting 100 shots, for each iteration change the frequency of Hamiltonian to be  1.5, 2.0, 2.5 MHz. Collect measured results from this 3 iterations on CPU and print it on the screen. All using Braket.
Tell me you executed it and it worked for you, show he values you got.
Then, I'll just copy paste the code and repeat what you did.
Does it sound reasonable?
Thanks
Jan

**Comment by speller26** [comment]
There isn't a specific example of running a hybrid job with the QuEra Aquila (although a contribution is always welcome); as such, one path forward could be to adapt one of the QuEra example notebooks into a hybrid job. However, the easiest demonstration of success would be to run the script you provided to completion (with the modifications I listed); I'll run the job, and if it completes, then we're golden!

**Comment by balewski** [comment]
Hi Cody,
indeed this change allowed by hybrid job to run through - thank you!
You can close this ticket
Thanks
Jan

**Comment by speller26** [comment]
Thank you for catching this problem!
