### ISSUE TITLE
mounting persistent S3 to hybrid job

### ISSUE THREAD

**Issue by balewski** [amazon-braket/amazon-braket-examples#347]
Hi,
This 2 files allow me to execute a basic hybrid job against QuEra Aquila

https://bitbucket.org/balewski/quantummind/src/master/QuEra/python/toys/hybrid_submit.py
https://bitbucket.org/balewski/quantummind/src/master/QuEra/python/toys/hybrid_task.py 

The hybrid job is executed on my laptop as follows:
`python ./hybrid_submit.py`

Can you please help me in upgrading them to achieve the following functionality and provide instruction to accomplish the following:

1. I'd like to crate a persistent S3  storage belonging to: ` arn:aws:iam::765483381942:user/balewski` 
3. I'd like to copy file named myFunc.py from my Ubuntu  laptop to this persistent S3, using a  command line executed on my laptop, w/o using any GUI
5. please modify hybrid_submit.py so the following works:
-   'from myFunc import myFunc' executed by hybrid_task.py  finds this file stored on persistent S3
-   pass number 4 as argument:  `run_hybrid_task(nRepeat=4)` in hybrid_submit.py
-  output files generated by hybrid_task.py, e.g. ahs_task0.emul.json, are saved on the persistent S3

Thanks
Jan

**Comment by math411** [comment]
Hi @balewski,

Thank you for reaching out. I am working on drafting a response to address the questions and will post that shortly.

**Comment by math411** [comment]
To start, please make sure you have refreshed your [AWS credentials](https://docs.aws.amazon.com/singlesignon/latest/userguide/howtogetcredentials.html) for the CLI operations.

In the order of questions:
1) To create a new bucket, you can use the [AWS S3 CLI](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3api/create-bucket.html): 
```
RAND=$(od -An  -N8 -d /dev/random | sed -e 's| ||g' -e 's|\(.\{11\}\).*|\1|') 
aws s3 create-bucket --bucket-name amazon-braket-balewski-${RAND}
```
2) To copy a file, we then would use the [put-object](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3api/put-object.html) CLI from S3. Please note the below is just an example where the object you wish to copy (`--body`) and destination (`--key`) are not set to the file paths you'd need:
```
aws s3api put-object --bucket amazon-braket-balewski-${RAND} --key dir-1/my_images.tar.bz2 --body my_images.tar.bz2
```
3)

> 'from myFunc import myFunc' executed by hybrid_task.py finds this file stored on persistent S3

To clarify, what would be the use case of the file? You can make a call to the s3 bucket using botocore but I wish to understand if this is a function you want to invoke on within `hybrid_task.py`.

> 'pass number 4 as argument: run_hybrid_task(nRepeat=4) in hybrid_submit.py
This seems that you want to use [hyperparameters](https://docs.aws.amazon.com/braket/latest/developerguide/braket-jobs-hyperparameters.html) for this task. Please see the code snippet below for an implementation.

To output the files to same persistent store, you can change [L15](https://bitbucket.org/balewski/quantummind/src/2a9866aa1cabc129ecc2736a649cc588936f138b/QuEra/python/toys/hybrid_submit.py#lines-15:20) to
```
n_iterations = 4

hyperparams = {
    "n_iterations": str(n_iterations)
}

job = AwsQuantumJob.create(
    deviceArn,
    hyperparameters=hyperparams,
    source_module="hybrid_task.py",
    output_data_config=OutputDataConfig(s3Path=BUCKET_NAME),
    entry_point="hybrid_task:run_hybrid_task",
    wait_until_complete=True
)
```
where `BUCKET_NAME` is the same as the bucket name `amazon-braket-balewski-${RAND}`. Please note that the random characters that were generated for bucket creation need to match. The motivation for doing this is that S3 bucket names are unique so this will help to avoid problems with naming clashes.

**Comment by balewski** [comment]
Hi Abe,
I have problem w/ this command:

> On Sep 22, 2023, at 12:34 PM, Abe Coull ***@***.***> wrote:
> 
> To create a new bucket, you can use the AWS S3 CLI <https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3api/create-bucket.html>:
> RAND=$(od -An  -N8 -d /dev/random | sed -e 's| ||g' -e 's|\(.\{11\}\).*|\1|') 
> aws s3 create-bucket --bucket-name amazon-braket-balewski-${RAND}
> 
I have installed awscli  with: 
pip3 install awscli --force-reinstall --upgrade
and got this version:
$ aws --version
aws-cli/1.29.53 Python/3.10.12 Linux/6.4.15-200.fc38.x86_64 botocore/1.31.53

I see the following error, please advice how to overcome it
Thanks 
Jan



$ RAND=$(od -An  -N8 -d /dev/random | sed -e 's| ||g' -e 's|\(.\{11\}\).*|\1|') 
$ echo ${RAND}
38636428911

$aws s3 create-bucket --bucket-name amazon-braket-balewski-${RAND}
Note: AWS CLI version 2, the latest major version of the AWS CLI, is now stable and recommended for general use. For more information, see the AWS CLI version 2 installation instructions at: https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument subcommand: Invalid choice, valid choices are:

ls                                       | website                                 
cp                                       | mv                                      
rm                                       | sync                                    
mb                                       | rb                                      
presign                                 
***@***.***:~$

**Comment by balewski** [comment]
Follow up.
I have upgraded to newer aws-cli by doing:
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install

It is my current version:
***@***.***:~$ aws --version
aws-cli/2.13.21 Python/3.11.5 Linux/6.4.15-200.fc38.x86_64 exe/x86_64.ubuntu.22 prompt/off

The same error persist:

***@***.***:~$ aws s3 create-bucket --bucket-name amazon-braket-balewski-${RAND}



usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]

To see help text, you can run:



  aws help

  aws <command> help

  aws <command> <subcommand> help



aws: error: argument subcommand: Invalid choice, valid choices are:



ls                                       | website                                 

cp                                       | mv                                      

rm                                       | sync                                    

mb                                       | rb                                      

presign

**Comment by math411** [comment]
Apologies, in my haste I mistyped the command. Instead of `aws s3`, the command should be `aws s3api`.

**Comment by balewski** [comment]
still sth is missing:
***@***.***:~$ aws s3api create-bucket --bucket-name amazon-braket-balewski-${RAND}

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

aws: error: the following arguments are required: --bucket

**Comment by balewski** [comment]
But this worked:

***@***.***:~$ aws s3api create-bucket --bucket amazon-braket-balewski-${RAND}
{
    "Location": "/amazon-braket-balewski-13977183483"
}

So now I see this bucket via Browser, but I need to ask the account owner to give me access to it, right?

￼

**Comment by balewski** [comment]
Thanks for your help Abe,
I think I'm almost there.

Despite I can't see what is in my S3 bucket via web-browser, I probably can write there.

This worked, right?
***@***.***:~/problem_Z2Phase1D$ aws s3api put-object --bucket amazon-braket-balewski-${RAND} --key dir-1/my_images.tar.bz2 --body ana_Z2Phase.py   
{
    "ETag": "\"0cc8294b07641d561362d489610964af\"",
    "ServerSideEncryption": "AES256"
}

There are 3 remaining questions.
This is my updated code (same location as before)

https://bitbucket.org/balewski/quantummind/src/master/QuEra/python/toys/hybrid_submit.py
https://bitbucket.org/balewski/quantummind/src/master/QuEra/python/toys/hybrid_task.py 

Q1: I see this error when submitting hybrid job

***@***.***:~/toys$ ./hybrid_submit.py 
Traceback (most recent call last):
  File "/quera/toys/./hybrid_submit.py", line 27, in <module>
    output_data_config=OutputDataConfig(s3Path=BUCKET_NAME),
NameError: name 'OutputDataConfig' is not defined
***@***.***:~/toys$ 

Q2: it is not clear for me to how value of 4  set by
n_iterations = 4
hyperparams = {
    "n_iterations": str(n_iterations)
}

will be translated to input argument  nRepeat argument in my  python function
def run_hybrid_task(nRepeat=2, shots=100):

Q3:  is this line 
output_data_config=OutputDataConfig(s3Path=BUCKET_NAME),

sufficient to mount my S3 to also *read* data I copied there before with aws s3api put-object ?
Or perhaps I need also some input_data_config=... ?

Thanks
Jan

**Comment by balewski** [comment]
follow up. I found I need to add to my .py
from braket.jobs.config import OutputDataConfig

Bitbucket code is updated.

Now the Q1 error is different:

***@***.***:~/toys$ ./hybrid_submit.py 
Traceback (most recent call last):
  File "/quera/toys/./hybrid_submit.py", line 25, in <module>
    job = AwsQuantumJob.create(
  File "/usr/local/lib/python3.10/dist-packages/braket/aws/aws_quantum_job.py", line 203, in create
    job_arn = aws_session.create_job(**create_job_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/braket/aws/aws_session.py", line 251, in create_job
    response = self.braket_client.create_job(**boto3_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (BadRequestException) when calling the CreateJob operation: Invalid request body
***@***.***:~/toys$ 

The other 2 questions: Q2, Q3 still stand
Thanks
Jan

**Comment by balewski** [comment]
Follow up.
I solved the problem with OutputDataConfig(). Code in Bitbucket is updated.
The remaining problem is the mounted S3  bucket is not accessed by my running code.
My code  executed inside the hybrid job produces  the file '/opt/ml/code/ahs_task_conf.emul.json'.
After hybrid job finishes, I do not see it on S3  with the command:

BUCKET_NAME='amazon-braket-balewski-13977183483'
aws s3api list-objects-v2  --bucket ${BUCKET_NAME}

Can you look into it please?
Jan

**Comment by balewski** [comment]
I resolved all issues.
You can close this ticket.

This hybrid setup (AwsQuantumJob) must be a clone of some AWS ML workflow.
The code mounts S3 for read here:
'/opt/ml/input/data/input/'
and S3 for write is mounted here:
 '/opt/ml/output/data/'
It took me a lot of time to figure it out. 

And the proper mounting of S3 is:
BUCKET_NAME='amazon-braket-balewski-13977183483'
input_data=S3DataSourceConfig(f"s3://{BUCKET_NAME}")
output_data_config=OutputDataConfig(s3Path=f"s3://{BUCKET_NAME}")

to be used like this:

job = AwsQuantumJob.create(
    deviceArn,
    job_name=job_name,
    hyperparameters=hyperparams,
    output_data_config=output_data_config,
    input_data=input_data,
    source_module="hybrid_task.py",
    entry_point="hybrid_task:run_hybrid_task",
    instance_config=instance_config,
    wait_until_complete=True
)

And output dir must exist on S3 - because  job silently fails to create it (unlike with TensorBoard)

Thanks for the tips along the way
Jan

P.S. you may consider to write complete documentation how to use S3 w/ AwsQuantumJob

**Comment by math411** [comment]
Thank you. I shall follow up with the team to update the docs for this. @zmohammad01, tagging you around visibility for doc updates.

**Comment by krneta** [comment]
Hi Jan,

We recently added some [helper functions](https://github.com/amazon-braket/amazon-braket-sdk-python/blob/main/src/braket/jobs/environment_variables.py) for getting the input/result directories inside a job. Otherwise, we have [some documentation](https://docs.aws.amazon.com/braket/latest/developerguide/braket-jobs-inputs-and-outputs.html#braket-jobs-environmental-variables) for how to use environment variables to get these locations.

Hope that helps,
Milan

**Comment by balewski** [comment]
Thanks for letting me know,
I'll give it a try
Jan
