### ISSUE TITLE
Braket is not respecting my choice of measured qubits

### ISSUE THREAD

**Issue by balewski** [amazon-braket/amazon-braket-examples#533]
**Describe the bug**
Braket is not respecting my choice of measured qubits. It measures all 3 qubits and changes my order of measurement. This circuit produces:  Counter({'110': 7, '000': 3}) , but it should produce :  Counter({'01': 7, '00': 3})

```
qc_br = Circuit()
qc_br.h(0).cnot(0, 1).x(2).x(2)
qc_br.probability(target=[2,1])
```

**To Reproduce**
```
from braket.aws import AwsDevice
device = AwsDevice("arn:aws:braket:::device/quantum-simulator/amazon/sv1")
from braket.circuits import Circuit
qc_br = Circuit()
qc_br.h(0).cnot(0, 1).x(2).x(2)
qc_br.probability(target=[1,2])
print(qc_br)
print('\nMeasured qubits:',qc_br._qubit_observable_mapping)
job = device.run(qc_br, shots=10)
jobRes=job.result()
print('M: counts',jobRes.measurement_counts)
```

**Expected behavior**
Counter({'01': 7, '00': 3})

**System information (please complete the following information as applicable):**
Ubuntu 22.04
core@a53c3c6fe9f2:~$ pip3 list |grep bra
amazon-braket-default-simulator 1.21.0
amazon-braket-schemas           1.20.2
amazon-braket-sdk               1.74.0
qbraid                          0.5.3
core@a53c3c6fe9f2:~$ python3 -V
Python 3.10.12

**Comment by balewski** [comment]
I understand and will test it. Thank you.
But is this a good strategy? 
2 problematic examples:
a) how do  I encode a circuit with several mid circuit measurements and feed-forward logic?  Such circuit has more measurements than the number of qubits.
b)Say I construct a 70 qubit circuit on Aspen-M-3 which  for which I want to measure only 10 qubits and 60 qubits serve as ancilla. And I run a 100k shots task. If you measure all 70 qubits for each shot you will generate ~100k different bitstrings, whereas I really want to see just 2^10=1k  different bitstrings. Why storing and transferring so much data?

**Comment by peterkomar-aws** [comment]
Hi,

a) Mid-circuit measurement is not implemented on Braket today. OpenQasm3 seems versatile enough to handle this, but I do not wish to speculate.
b) Yes. Once the size of the output becomes unwieldy, transferring only the requested measurements sounds like a good idea.
